language: python
python:
  - "2.7"
services:
  - couchdb
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage
  - pep8
  - flake8
after_success:
  - coveralls
